-- Set default schema to use for the following queries
SET search_path TO "utility";

DROP TABLE IF EXISTS "language";

CREATE TABLE "language" (
  "id" char(2) NOT NULL PRIMARY KEY,
  "name" varchar(50) NOT NULL,
  "native" varchar(50) NOT NULL,
  "rtl" bool NOT NULL DEFAULT FALSE,
  "created_at" timestamptz NOT NULL DEFAULT NOW(),
  "updated_at" timestamptz NOT NULL DEFAULT NOW()
);

-- https://en.wikipedia.org/wiki/ISO_639-1
COMMENT ON COLUMN language.id IS 'ISO 639-1';

CREATE TRIGGER set_language_updated_at before
UPDATE ON "language" FOR each ROW EXECUTE PROCEDURE set_current_timestamp_updated_at();

INSERT INTO "language" ("id", "name", "native", "rtl")
VALUES ('af', 'Afrikaans', 'Afrikaans', false),
  ('am', 'Amharic', 'አማርኛ', false),
  ('ar', 'Arabic', 'العربية', TRUE),
  ('ay', 'Aymara', 'Aymar', false),
  (
    'az',
    'Azerbaijani',
    'Azərbaycanca / آذربايجان',
    false
  ),
  ('be', 'Belarusian', 'Беларуская', false),
  ('bg', 'Bulgarian', 'Български', false),
  ('bi', 'Bislama', 'Bislama', false),
  ('bn', 'Bengali', 'বাংলা', false),
  ('bs', 'Bosnian', 'Bosanski', false),
  ('ca', 'Catalan', 'Català', false),
  ('ch', 'Chamorro', 'Chamoru', false),
  ('cs', 'Czech', 'Čeština', false),
  ('da', 'Danish', 'Dansk', false),
  ('de', 'German', 'Deutsch', false),
  ('dv', 'Divehi', 'ދިވެހިބަސް', TRUE),
  ('dz', 'Dzongkha', 'ཇོང་ཁ', false),
  ('el', 'Greek', 'Ελληνικά', false),
  ('en', 'English', 'English', false),
  ('es', 'Spanish', 'Español', false),
  ('et', 'Estonian', 'Eesti', false),
  ('eu', 'Basque', 'Euskara', false),
  ('fa', 'Persian', 'فارسی', TRUE),
  ('ff', 'Peul', 'Fulfulde', false),
  ('fi', 'Finnish', 'Suomi', false),
  ('fj', 'Fijian', 'Na Vosa Vakaviti', false),
  ('fo', 'Faroese', 'Føroyskt', false),
  ('fr', 'French', 'Français', false),
  ('ga', 'Irish', 'Gaeilge', false),
  ('gl', 'Galician', 'Galego', false),
  ('gn', 'Guarani', 'Avañe''ẽ', false),
  ('gv', 'Manx', 'Gaelg', false),
  ('he', 'Hebrew', 'עברית', TRUE),
  ('hi', 'Hindi', 'हिन्दी', false),
  ('hr', 'Croatian', 'Hrvatski', false),
  ('ht', 'Haitian', 'Krèyol ayisyen', false),
  ('hu', 'Hungarian', 'Magyar', false),
  ('hy', 'Armenian', 'Հայերեն', false),
  ('id', 'Indonesian', 'Bahasa Indonesia', false),
  ('is', 'Icelandic', 'Íslenska', false),
  ('it', 'Italian', 'Italiano', false),
  ('ja', 'Japanese', '日本語', false),
  ('ka', 'Georgian', 'ქართული', false),
  ('kg', 'Kongo', 'KiKongo', false),
  ('kk', 'Kazakh', 'Қазақша', false),
  ('kl', 'Greenlandic', 'Kalaallisut', false),
  ('km', 'Cambodian', 'ភាសាខ្មែរ', false),
  ('ko', 'Korean', '한국어', false),
  ('ku', 'Kurdish', 'Kurdî / كوردی', TRUE),
  ('ky', 'Kyrgyz', 'Кыргызча', false),
  ('la', 'Latin', 'Latina', false),
  ('lb', 'Luxembourgish', 'Lëtzebuergesch', false),
  ('ln', 'Lingala', 'Lingála', false),
  ('lo', 'Laotian', 'ລາວ / Pha xa lao', false),
  ('lt', 'Lithuanian', 'Lietuvių', false),
  ('lu', 'Luba-Katanga', 'Tshiluba', false),
  ('lv', 'Latvian', 'Latviešu', false),
  ('mg', 'Malagasy', 'Malagasy', false),
  ('mh', 'Marshallese', 'Kajin Majel / Ebon', false),
  ('mi', 'Maori', 'Māori', false),
  ('mk', 'Macedonian', 'Македонски', false),
  ('mn', 'Mongolian', 'Монгол', false),
  ('ms', 'Malay', 'Bahasa Melayu', false),
  ('mt', 'Maltese', 'bil-Malti', false),
  ('my', 'Burmese', 'မြန်မာစာ', false),
  ('na', 'Nauruan', 'Dorerin Naoero', false),
  ('nb', 'Norwegian Bokmål', 'Norsk bokmål', false),
  ('nd', 'North Ndebele', 'Sindebele', false),
  ('ne', 'Nepali', 'नेपाली', false),
  ('nl', 'Dutch', 'Nederlands', false),
  (
    'nn',
    'Norwegian Nynorsk',
    'Norsk nynorsk',
    false
  ),
  ('no', 'Norwegian', 'Norsk', false),
  ('nr', 'South Ndebele', 'isiNdebele', false),
  ('ny', 'Chichewa', 'Chi-Chewa', false),
  ('oc', 'Occitan', 'Occitan', false),
  (
    'pa',
    'Panjabi / Punjabi',
    'ਪੰਜਾਬੀ / पंजाबी / پنجابي',
    false
  ),
  ('pl', 'Polish', 'Polski', false),
  ('ps', 'Pashto', 'پښتو', TRUE),
  ('pt', 'Portuguese', 'Português', false),
  ('qu', 'Quechua', 'Runa Simi', false),
  ('rn', 'Kirundi', 'Kirundi', false),
  ('ro', 'Romanian', 'Română', false),
  ('ru', 'Russian', 'Русский', false),
  ('rw', 'Rwandi', 'Kinyarwandi', false),
  ('sg', 'Sango', 'Sängö', false),
  ('si', 'Sinhalese', 'සිංහල', false),
  ('sk', 'Slovak', 'Slovenčina', false),
  ('sl', 'Slovenian', 'Slovenščina', false),
  ('sm', 'Samoan', 'Gagana Samoa', false),
  ('sn', 'Shona', 'chiShona', false),
  ('so', 'Somalia', 'Soomaaliga', false),
  ('sq', 'Albanian', 'Shqip', false),
  ('sr', 'Serbian', 'Српски', false),
  ('ss', 'Swati', 'SiSwati', false),
  ('st', 'Southern Sotho', 'Sesotho', false),
  ('sv', 'Swedish', 'Svenska', false),
  ('sw', 'Swahili', 'Kiswahili', false),
  ('ta', 'Tamil', 'தமிழ்', false),
  ('tg', 'Tajik', 'Тоҷикӣ', false),
  ('th', 'Thai', 'ไทย / Phasa Thai', false),
  ('ti', 'Tigrinya', 'ትግርኛ', false),
  ('tk', 'Turkmen', 'Туркмен / تركمن', false),
  ('tn', 'Tswana', 'Setswana', false),
  ('to', 'Tonga', 'Lea Faka-Tonga', false),
  ('tr', 'Turkish', 'Türkçe', false),
  ('ts', 'Tsonga', 'Xitsonga', false),
  ('uk', 'Ukrainian', 'Українська', false),
  ('ur', 'Urdu', 'اردو', TRUE),
  ('uz', 'Uzbek', 'Ўзбек', false),
  ('ve', 'Venda', 'Tshivenḓa', false),
  ('vi', 'Vietnamese', 'Tiếng Việt', false),
  ('xh', 'Xhosa', 'isiXhosa', false),
  ('zh', 'Chinese', '中文', false),
  ('zu', 'Zulu', 'isiZulu', false);